# Combinação de classificadores

In [12]:
import pickle

In [15]:
with open('../../assets/credit.pkl', 'rb') as f:
  X_credit_train, y_credit_train, X_credit_test, y_credit_test = pickle.load(f)

In [16]:
import numpy as np

In [17]:
X_credit = np.concatenate((X_credit_train, X_credit_test), axis = 0)
y_credit = np.concatenate((y_credit_train, y_credit_test), axis = 0)

In [18]:
neural_network = pickle.load(open('rede_neural_finalizado.sav', 'rb'))
tree = pickle.load(open('arvore_finalizado.sav', 'rb'))
svm = pickle.load(open('svm_finalizado.sav', 'rb'))

In [19]:
new_record = X_credit[1999]
new_record

array([-1.03572293, -0.93978209,  0.04244312])

In [20]:
new_record.shape

(3,)

In [21]:
new_record = new_record.reshape(1, -1)
new_record.shape

(1, 3)

In [22]:
new_record

array([[-1.03572293, -0.93978209,  0.04244312]])

In [29]:
result_neural_network = neural_network.predict(new_record)

In [30]:
result_tree = tree.predict(new_record)

In [39]:
result_svm = svm.predict(new_record)

In [47]:
results = np.concatenate((result_neural_network, result_tree, result_svm))

array([1, 1, 1])

In [48]:
pay = (results == 0).sum()
not_pay = (results == 1).sum()

pay, not_pay

(0, 3)

In [49]:
if pay > not_pay:
  print("Cliente pagará o empréstimo")
elif pay == not_pay:
  print("Empate")
else:
  print("Cliente não pagará o empréstimo")

Cliente não pagará o empréstimo
