In [1]:
%pip install plotly -U -q
%pip install seaborn -q
%pip install matplotlib -q
%pip install pandas -q
%pip install numpy -q

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
base_health_insurance = pd.read_csv("../../assets/plano_saude2.csv")

In [4]:
X_health_insurance = base_health_insurance.iloc[:, 0:1].values
y_health_insurance = base_health_insurance.iloc[:, 1].values

In [5]:
X_health_insurance

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [6]:
y_health_insurance

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [13]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=4)

X_health_insurance_poly = poly.fit_transform(X_health_insurance)

In [23]:
X_health_insurance_poly

array([[1.0000000e+00, 1.8000000e+01, 3.2400000e+02, 5.8320000e+03,
        1.0497600e+05],
       [1.0000000e+00, 2.3000000e+01, 5.2900000e+02, 1.2167000e+04,
        2.7984100e+05],
       [1.0000000e+00, 2.8000000e+01, 7.8400000e+02, 2.1952000e+04,
        6.1465600e+05],
       [1.0000000e+00, 3.3000000e+01, 1.0890000e+03, 3.5937000e+04,
        1.1859210e+06],
       [1.0000000e+00, 3.8000000e+01, 1.4440000e+03, 5.4872000e+04,
        2.0851360e+06],
       [1.0000000e+00, 4.3000000e+01, 1.8490000e+03, 7.9507000e+04,
        3.4188010e+06],
       [1.0000000e+00, 4.8000000e+01, 2.3040000e+03, 1.1059200e+05,
        5.3084160e+06],
       [1.0000000e+00, 5.3000000e+01, 2.8090000e+03, 1.4887700e+05,
        7.8904810e+06],
       [1.0000000e+00, 5.8000000e+01, 3.3640000e+03, 1.9511200e+05,
        1.1316496e+07],
       [1.0000000e+00, 6.3000000e+01, 3.9690000e+03, 2.5004700e+05,
        1.5752961e+07]])

In [15]:
from sklearn.linear_model import LinearRegression

polynomial_regression = LinearRegression()
polynomial_regression.fit(X_health_insurance_poly, y_health_insurance)

LinearRegression()

In [16]:
polynomial_regression.intercept_

16561.97463791193

In [17]:
polynomial_regression.coef_

array([ 0.00000000e+00, -2.12242253e+03,  9.90404199e+01, -1.95058276e+00,
        1.40792541e-02])

In [19]:
new_record = [[40]]
new_record = poly.transform(new_record)

In [20]:
polynomial_regression.predict(new_record)

array([1335.33958015])

In [21]:
predictions = polynomial_regression.predict(X_health_insurance_poly)
predictions

array([ 549.65035464,  345.85081575,  616.53845992,  975.8391595 ,
       1249.06759853, 1472.7272727 , 1894.51048941, 2973.2983677 ,
       5379.16083828, 9993.35664357])

In [22]:
graphic = px.scatter(x=X_health_insurance[:, 0], y=y_health_insurance)
graphic.add_scatter(
    x=X_health_insurance[:, 0], y=predictions, name="Regressão")
graphic.show()