In [1]:
%pip install plotly -U -q
%pip install seaborn -q
%pip install matplotlib -q
%pip install pandas -q
%pip install numpy -q

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Base de dados para plano de saúde

In [3]:
base_health_insurance = pd.read_csv("../../assets/plano_saude2.csv")

In [4]:
X_health_insurance = base_health_insurance.iloc[:, 0:1].values
y_health_insurance = base_health_insurance.iloc[:, 1].values

In [5]:
X_health_insurance

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]])

In [6]:
y_health_insurance

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100])

In [7]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=4)

X_health_insurance_poly = poly.fit_transform(X_health_insurance)

In [8]:
X_health_insurance_poly

array([[1.0000000e+00, 1.8000000e+01, 3.2400000e+02, 5.8320000e+03,
        1.0497600e+05],
       [1.0000000e+00, 2.3000000e+01, 5.2900000e+02, 1.2167000e+04,
        2.7984100e+05],
       [1.0000000e+00, 2.8000000e+01, 7.8400000e+02, 2.1952000e+04,
        6.1465600e+05],
       [1.0000000e+00, 3.3000000e+01, 1.0890000e+03, 3.5937000e+04,
        1.1859210e+06],
       [1.0000000e+00, 3.8000000e+01, 1.4440000e+03, 5.4872000e+04,
        2.0851360e+06],
       [1.0000000e+00, 4.3000000e+01, 1.8490000e+03, 7.9507000e+04,
        3.4188010e+06],
       [1.0000000e+00, 4.8000000e+01, 2.3040000e+03, 1.1059200e+05,
        5.3084160e+06],
       [1.0000000e+00, 5.3000000e+01, 2.8090000e+03, 1.4887700e+05,
        7.8904810e+06],
       [1.0000000e+00, 5.8000000e+01, 3.3640000e+03, 1.9511200e+05,
        1.1316496e+07],
       [1.0000000e+00, 6.3000000e+01, 3.9690000e+03, 2.5004700e+05,
        1.5752961e+07]])

In [9]:
from sklearn.linear_model import LinearRegression

polynomial_regression = LinearRegression()
polynomial_regression.fit(X_health_insurance_poly, y_health_insurance)

LinearRegression()

In [10]:
polynomial_regression.intercept_

16561.97463791193

In [11]:
polynomial_regression.coef_

array([ 0.00000000e+00, -2.12242253e+03,  9.90404199e+01, -1.95058276e+00,
        1.40792541e-02])

In [12]:
new_record = [[40]]
new_record = poly.transform(new_record)

In [13]:
polynomial_regression.predict(new_record)

array([1335.33958015])

In [14]:
predictions = polynomial_regression.predict(X_health_insurance_poly)
predictions

array([ 549.65035464,  345.85081575,  616.53845992,  975.8391595 ,
       1249.06759853, 1472.7272727 , 1894.51048941, 2973.2983677 ,
       5379.16083828, 9993.35664357])

In [15]:
graphic = px.scatter(x=X_health_insurance[:, 0], y=y_health_insurance)
graphic.add_scatter(
    x=X_health_insurance[:, 0], y=predictions, name="Regressão")
graphic.show()

# Base de dados de preços das casas

In [17]:
base_house_prices = pd.read_csv("../../assets/house_prices.csv")

In [20]:
base_house_prices.drop(columns="date", inplace=True)
base_house_prices

id     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0      7129300520  221900.0         3       1.00         1180      5650   
1      6414100192  538000.0         3       2.25         2570      7242   
2      5631500400  180000.0         2       1.00          770     10000   
3      2487200875  604000.0         4       3.00         1960      5000   
4      1954400510  510000.0         3       2.00         1680      8080   
...           ...       ...       ...        ...          ...       ...   
21608   263000018  360000.0         3       2.50         1530      1131   
21609  6600060120  400000.0         4       2.50         2310      5813   
21610  1523300141  402101.0         2       0.75         1020      1350   
21611   291310100  400000.0         3       2.50         1600      2388   
21612  1523300157  325000.0         2       0.75         1020      1076   

       floors  waterfront  view  condition  grade  sqft_above  sqft_basement  \
0         1.0           0     0          3      7        1180              0   
1         2.0           0     0          3      7        2170            400   
2         1.0           0     0          3      6         770              0   
3         1.0           0     0          5      7        1050            910   
4         1.0           0     0          3      8        1680              0   
...       ...         ...   ...        ...    ...         ...            ...   
21608     3.0           0     0          3      8        1530              0   
21609     2.0           0     0          3      8        2310              0   
21610     2.0           0     0          3      7        1020              0   
21611     2.0           0     0          3      8        1600              0   
21612     2.0           0     0          3      7        1020              0   

       yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0          1955             0    98178  47.5112 -122.257           1340   
1          1951          1991    98125  47.7210 -122.319           1690   
2          1933             0    98028  47.7379 -122.233           2720   
3          1965             0    98136  47.5208 -122.393           1360   
4          1987             0    98074  47.6168 -122.045           1800   
...         ...           ...      ...      ...      ...            ...   
21608      2009             0    98103  47.6993 -122.346           1530   
21609      2014             0    98146  47.5107 -122.362           1830   
21610      2009             0    98144  47.5944 -122.299           1020   
21611      2004             0    98027  47.5345 -122.069           1410   
21612      2008             0    98144  47.5941 -122.299           1020   

       sqft_lot15  
0            5650  
1            7639  
2            8062  
3            5000  
4            7503  
...           ...  
21608        1509  
21609        7200  
21610        2007  
21611        1287  
21612        1357  

[21613 rows x 20 columns]

In [29]:
X_house_prices = base_house_prices.iloc[:, 2:18].values
y_house_prices = base_house_prices.iloc[:, 1].values

In [36]:
X_house_prices

array([[ 3.00000e+00,  1.00000e+00,  1.18000e+03, ...,  9.81780e+04,
         4.75112e+01, -1.22257e+02],
       [ 3.00000e+00,  2.25000e+00,  2.57000e+03, ...,  9.81250e+04,
         4.77210e+01, -1.22319e+02],
       [ 2.00000e+00,  1.00000e+00,  7.70000e+02, ...,  9.80280e+04,
         4.77379e+01, -1.22233e+02],
       ...,
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75944e+01, -1.22299e+02],
       [ 3.00000e+00,  2.50000e+00,  1.60000e+03, ...,  9.80270e+04,
         4.75345e+01, -1.22069e+02],
       [ 2.00000e+00,  7.50000e-01,  1.02000e+03, ...,  9.81440e+04,
         4.75941e+01, -1.22299e+02]])

In [37]:
y_house_prices

array([221900., 538000., 180000., ..., 402101., 400000., 325000.])

In [39]:
from sklearn.model_selection import train_test_split

X_house_prices_train, X_house_prices_test, y_house_prices_train, y_house_prices_test = train_test_split(X_house_prices, y_house_prices, test_size=0.3, random_state=0)

In [41]:
X_house_prices_train.shape, y_house_prices_train.shape

((15129, 16), (15129,))

In [43]:
X_house_prices_test.shape, y_house_prices_test.shape

((6484, 16), (6484,))

In [44]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)
X_house_prices_train_poly = poly.fit_transform(X_house_prices_train)
X_house_prices_test_poly = poly.transform(X_house_prices_test)

In [45]:
polynomial_regression = LinearRegression()
polynomial_regression.fit(X_house_prices_train_poly, y_house_prices_train)

LinearRegression()

In [46]:
polynomial_regression.score(X_house_prices_train_poly, y_house_prices_train)

0.8179326929387845

In [47]:
polynomial_regression.score(X_house_prices_test_poly, y_house_prices_test)

0.8153239785653597

In [48]:
predictions = polynomial_regression.predict(X_house_prices_test_poly)
predictions

array([ 386209.87734985, 1991245.51792908,  578932.19153595, ...,
        432998.13909912,  234019.63778687,  123591.43396759])

In [49]:
y_house_prices_test

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [50]:
from sklearn.metrics import mean_absolute_error

In [51]:
mean_absolute_error(y_house_prices_test, predictions)

101228.59452984555